# Generated by Django 6.1.1 on 2026-09-15 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrio', models.CharField(choices=[('Barrio 1', 'Barrio 1'), ('Barrio 2', 'Barrio 2'), ('Barrio 3', 'Barrio 3')], max_length=100, verbose_name='Barrio')),
                ('categoria', models.CharField(choices=[('Emprendimiento', 'Emprendimiento'), ('Artista', 'Artista'), ('Danza', 'Danza'), ('Juegos Tradicionales', 'Juegos Tradicionales'), ('Otra Propuesta', 'Otra Propuesta')], max_length=100, verbose_name='Categoría')),
                ('nombre_aporte', models.CharField(max_length=200, verbose_name='Nombre del Aporte / Emprendimiento')),
                ('responsable', models.CharField(max_length=150, verbose_name='Persona Responsable')),
                ('contacto', models.CharField(max_length=100, verbose_name='Teléfono / Contacto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción u Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Aporte',
                'verbose_name_plural': 'Aportes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='BoletoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número / Identificador de Boleto')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('vendido', 'Vendido')], default='disponible', max_length=20, verbose_name='Estado')),
                ('comprador', models.CharField(blank=True, max_length=150, verbose_name='Comprador')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono Comprador')),
                ('fecha_venta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Venta')),
                ('notas', models.TextField(blank=True, verbose_name='Notas u Observaciones')),
            ],
            options={
                'verbose_name': 'Boleto Físico',
                'verbose_name_plural': 'Boletos Físicos',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudBoleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comprador', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('cedula', models.CharField(max_length=20, verbose_name='Cédula / Identificación')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad de Boletos')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=2.0, max_digits=6, verbose_name='Precio Unitario ($)')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total ($)')),
                ('comprobante', models.ImageField(upload_to='comprobantes/', verbose_name='Comprobante de Pago')),
                ('estado', models.CharField(choices=[('pendiente', 'En Revisión (Comprobante Subido)'), ('confirmado', 'Aprobado / Confirmado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('notas_admin', models.TextField(blank=True, verbose_name='Notas del Administrador')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Respuesta')),
            ],
            options={
                'verbose_name': 'Solicitud de Boleto Digital',
                'verbose_name_plural': 'Solicitudes de Boletos Digitales',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='BoletoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.CharField(max_length=50, unique=True, verbose_name='Código Único (QR)')),
                ('nombre_comprador', models.CharField(max_length=150, verbose_name='Nombre Comprador')),
                ('estado', models.CharField(choices=[('confirmado', 'VÁLIDO'), ('utilizado', 'UTILIZADO'), ('cancelado', 'CANCELADO')], default='confirmado', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_uso', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Uso en Puerta')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='Imagen QR')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos_digitales', to='feria.solicitudboleto', verbose_name='Solicitud de Origen')),
            ],
            options={
                'verbose_name': 'Boleto Digital',
                'verbose_name_plural': 'Boletos Digitales',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
