# Generated by Django 5.2.5 on 2026-09-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aporte',
            name='barrio',
            field=models.CharField(choices=[('Barrio 1', 'San Luis'), ('Barrio 2', 'Vista Hermosa'), ('Barrio 3', 'Quito Occidental')], max_length=100, verbose_name='Barrio'),
        ),
    ]
