# Generated by Django 5.2.5 on 2026-09-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feria', '0002_alter_aporte_barrio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aporte',
            name='barrio',
            field=models.CharField(choices=[('San Luis', 'San Luis'), ('Vista Hermosa', 'Vista Hermosa'), ('Quito Occidental', 'Quito Occidental')], max_length=100, verbose_name='Barrio'),
        ),
        migrations.AlterField(
            model_name='solicitudboleto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=6, verbose_name='Precio Unitario ($)'),
        ),
    ]
