# Generated by Django 5.2.5 on 2026-09-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feria', '0003_alter_aporte_barrio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudboleto',
            name='numero_comprobante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nro. de Comprobante / Referencia'),
        ),
    ]
